### PR TITLE
#21 feat add svg assets to the project

### PR DESCRIPTION
**Pull request by TheGuyWithoutH**
Here you will find the assets for the first part of the UI. You can see them in the ressource manager tab as follows :

image

It contains :
- the logos for the app launcher (already setup)
- the logos for the app
- the icons
- A background for the login

### CODE REVIEW

**Comment by lucamouchel** [comment]
Looks great!! 
to make it look better, i think we should remove the header with the app name on top of the screen
image
so that it looks like this 
image

you can do this by changing the line 
`<style name="Theme.CultureQuest" parent="Theme.MaterialComponents.DayNight.DarkActionBar">` into  
 `<style name="Theme.CultureQuest" parent="Theme.MaterialComponents.DayNight.NoActionBar">` in the two `themes.xml` files

`

**Review by lucamouchel — COMMENTED** [review]
Looks great!! 
to make it look better, i think we should remove the header with the app name on top of the screen
image
so that it looks like this 
image

you can do this by changing the line 
`<style name="Theme.CultureQuest" parent="Theme.MaterialComponents.DayNight.DarkActionBar">` into  
 `<style name="Theme.CultureQuest" parent="Theme.MaterialComponents.DayNight.NoActionBar">` in the two `themes.xml` files

`

**Comment by TheGuyWithoutH** [comment]
> Looks great!! 
> to make it look better, i think we should remove the header with the app name on top of the screen
> image
> so that it looks like this 
> image
> 
> you can do this by changing the line 
> `<style name="Theme.CultureQuest" parent="Theme.MaterialComponents.DayNight.DarkActionBar">` into  
>  `<style name="Theme.CultureQuest" parent="Theme.MaterialComponents.DayNight.NoActionBar">` in the two `themes.xml` files
> 
> `

Oh yes for sure! I did not touch anything on the activities, but for each one we should remove the header ! I will do it if you want!

**Review by lucamouchel — APPROVED** [review]

**Comment by TheGuyWithoutH** [comment]
I changed the header and also made the status bar transparent (sample code in `MainActivity.java`) to look like the following : 
image

**Review by lucamouchel — APPROVED** [review]

**Pull request merged**
