### PR TITLE
Feat: 107 add firebase storage emulator and refactor existing storage code

### PR DESCRIPTION
**Pull request by hmiranda-queiros**
This PR adds the usage of the Firebase storage emulator for the tests. It also refactors all the code and tests that were using the the Firebase storage by putting all the storage code in a single class.
Some functions and classes were also removed/split in order to be able to test them efficiently and to reuse them in other classes.

The diff coverage of this PR is bad because I moved lines of code that were already not tested previously.  However,  in this sprint everybody will implement the missing tests from previous sprints to increase coverage, so this will be solved later in the sprint.

### CODE REVIEW

**Review by TheGuyWithoutH — COMMENTED** [review]
Great changes! Good that you moved everything related to the storage in its own package. It is now cleaner. Is it just possible to improve the diff coverage?

**Comment by hmiranda-queiros** [comment]
> Great changes! Good that you moved everything related to the storage in its own package. It is now cleaner. Is it just possible to improve the diff coverage?

The overall coverage should normally be improved even if diff coverage is low because I created new tests and I did not write new code, I just refactored the code. I was not even supposed to write new tests it in this PR because it was just about refactoring already existing code :/ 
The diff coverage is bad because I moved lines of code that were already not tested previously. One of my next PR in this sprint will be to implement tests for all the functions that were previously forgotten by the team since the beginning.

**Review by TheGuyWithoutH — COMMENTED** [review]
Good to go!

**Comment by hmiranda-queiros** [comment]
> Maybe notify every member for the missing test instead of doing all yourself, so that you can go on to other tasks/aspects of the project

Ok good idea I will do that then !

**Review by TheGuyWithoutH — APPROVED** [review]
Good to go now!

**Pull request merged**
