### PR TITLE
Feat: Sign in page

### PR DESCRIPTION
**Pull request by lucamouchel**
Looks like this for now. (inspired by vivino -- same app concept than us but for wine)
image
and when signing in with google we go to the profile creation page. 

UPDATE: User can now select a profile picture before officially creating an account. Basically, user signs in with google, 
we display the email which is uneditable. The user can edit first and last name and add profile picture.

The library Picasso is really nice and easy to use, we just need the image uri or path to set a picture. Worth considering for future stuff when dealing with pics.

so now it looks like this: 
image

### CODE REVIEW

**Comment by TheGuyWithoutH** [comment]
Is it possible when using Google Auth to automatically get the name of the profile as well as its email?

**Comment by lucamouchel** [comment]
> Is it possible when using Google Auth to automatically get the name of the profile as well as its email?

yep we can I already do so in `ProfileCreatorActivity` even though there's still a lot of work to be done in that class

**Comment by TheGuyWithoutH** [comment]
I just thought of this : should we ask the entire name or should we just ask for a pseudo? Because a pseudo will be easier for the interface.

**Comment by lucamouchel** [comment]
> I just thought of this : should we ask the entire name or should we just ask for a pseudo? Because a pseudo will be easier for the interface.

yep we can do that. It's easier that's true

**Review by TheGuyWithoutH — APPROVED** [review]
Seems good to me, you can merge

**Pull request merged**
